run:
  # timeout for analysis, e.g. 30s
  timeout: 5m
  
  # include test files
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - misspell
    - goimports
    - gosec
    - unconvert
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gosec:
    excludes:
      - G404  # Use of weak random number generator

  gofmt:
    simplify: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
